cask_args appdir: '/Applications'

brew 'ag'
brew 'bash'
brew 'bat'
brew 'btop'
brew 'buf'
brew 'chafa'
brew 'curl'
brew 'duf'
brew 'dust'
brew 'eza'
brew 'fastfetch'
brew 'fd'
brew 'ffmpeg'
brew 'fzf'
brew 'git'
brew 'git-delta'
brew 'git-lfs'
brew 'gnu-sed'
brew 'go'
brew 'gping'
brew 'ipcalc'
brew 'jq'
brew 'lazygit'
brew 'lnav'
brew 'lux'
brew 'make'
brew 'mas'
brew 'neovim'
brew 'node'
brew 'openssh'
brew 'openssl'
brew 'powerlevel10k'
brew 'procs'
brew 'protobuf'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'ripgrep'
brew 'sd'
brew 'tldr'
brew 'tmux'
brew 'vivid'
brew 'xh'
brew 'yt-dlp'
brew 'zig'
brew 'zoxide'
brew 'zsh-autosuggestions'
brew 'zsh-fast-syntax-highlighting'

cask '1password'
cask 'alacritty'
cask 'appcleaner'
cask 'arc'
cask 'betterdisplay'
cask 'discord'
cask 'docker'
cask 'ghostty'
cask 'google-drive'
cask 'keka'
cask 'nikitabobko/tap/aerospace'
cask 'obsidian'
cask 'raycast'
cask 'shottr'
cask 'spotify'
cask 'stolendata-mpv'
cask 'transmission'
cask 'whatsapp'

mas 'Amphetamine', id: 937984704
mas 'Hidden Bar', id: 1452453066
mas 'iA Writer', id: 775737590
mas 'Kindle', id: 302584613
