cask_args appdir: '/Applications'

brew 'bash'
brew 'bat'
brew 'btop'
brew 'buf'
brew 'chafa'
brew 'curl'
brew 'duf'
brew 'dust'
brew 'eza'
brew 'fastfetch'
brew 'fd'
brew 'ffmpeg'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'git-lfs'
brew 'glow'
brew 'gnupg'
brew 'gnu-sed'
brew 'gping'
brew 'gum'
brew 'ipcalc'
brew 'jq'
brew 'lazygit'
brew 'lnav'
brew 'make'
brew 'mas'
brew 'mise'
brew 'mpv'
brew 'neovim'
brew 'openssh'
brew 'openssl'
brew 'pandoc'
brew 'powerlevel10k'
brew 'procs'
brew 'protobuf'
brew 'ripgrep'
brew 'sd'
brew 'sesh'
brew 'tlrc'
brew 'tmux'
brew 'vivid'
brew 'xh'
brew 'yt-dlp'
brew 'zoxide'
brew 'zsh-autosuggestions'
brew 'zsh-fast-syntax-highlighting'

cask '1password'
cask 'appcleaner'
cask 'ccleaner'
cask 'claude'
cask 'claude-code'
cask 'docker-desktop'
cask 'font-fira-code-nerd-font'
cask 'font-iosevka'
cask 'ghostty'
cask 'google-drive'
cask 'nikitabobko/tap/aerospace'
cask 'obsidian'
cask 'raycast'
cask 'shottr'
cask 'spotify'
cask 'transmission'
cask 'vivaldi'

mas 'Amphetamine', id: 937984704
mas 'Craft', id: 1487937127
mas 'Hidden Bar', id: 1452453066
mas 'iA Writer', id: 775737590
mas 'Kindle', id: 302584613
