# -- general -------------------------------------------------------------------

# TERM should be screen-* or tmux-*
set -g default-terminal "screen-256color"

# enbale 24-bit color
set -as terminal-overrides ',screen-256color:RGB'

#increase repeat timeout
set -sg repeat-time 600

# enable Vi key bindings in copy mode.
setw -g mode-keys vi

# change the default prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# -- display -------------------------------------------------------------------

# start window numbering at 1
set -g base-index 1

# make pane numbering consistent with windows
setw -g pane-base-index 1

# renumber windows sequentially after closing any of them
set -g renumber-windows on

# rename window to reflect current program
setw -g automatic-rename on

# set terminal title
set -g set-titles on
set -g set-titles-string '#W/#T'

# activity
set -g monitor-activity on
set -g visual-activity off

# -- Keybindings -------------------------------------------------------------------

unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded"

# use v and h for window splitting
unbind %
unbind v
unbind '"'
unbind h
bind v split-window -h -c '#{pane_current_path}'
bind h split-window -v -c '#{pane_current_path}'

# enable mouse support including pane focusing and selection support
set -g mouse on

# -- copy mode -----------------------------------------------------------------

bind -Tcopy-mode-vi 'v' send-keys -X begin-selection
bind -Tcopy-mode-vi 'y' send-keys -X copy-selection-and-cancel

# -- theme -----------------------------------------------------------------

# set the default theme variant
set -g @rose_pine_variant 'moon'
set -g @rose_pine_host 'on'
set -g @rose_pine_hostname_short 'on'
set -g @rose_pine_date_time '%Y-%m-%d %H:%M'
set -g @rose_pine_user 'off'
set -g @rose_pine_directory 'on'
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_bar_bg_disabled_color_option 'default'

set -g @rose_pine_only_windows 'off'
set -g @rose_pine_disable_active_window_menu 'on'
set -g @rose_pine_default_window_behavior 'on'
set -g @rose_pine_show_current_program 'on'
set -g @rose_pine_show_pane_directory 'on'
set -g @rose_pine_status_left_append_section ' '

# custom separators
set -g @rose_pine_right_separator '    '
# set -g @rose_pine_field_separator '  '
set -g @rose_pine_window_separator ' - '

# custom icons
set -g @rose_pine_window_status_separator '    ' # Changes the default icon that appears between window names

# -- plugins -------------------------------------------------------------------

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'rose-pine/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tpm'

# automatically install tmux plugin manager
if "test ! -d $XDG_DATA_HOME/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm $XDG_DATA_HOME/tmux/plugins/tpm && $XDG_DATA_HOME/tmux/plugins/tpm/bin/install_plugins'"

run "$XDG_DATA_HOME/tmux/plugins/tpm/tpm"
