# -- general -------------------------------------------------------------------

[general]
import = [
    "~/.config/alacritty/keybindings.toml",
    "~/.config/alacritty/themes/rose-pine/rose-pine-moon.toml",
]

# -- window -------------------------------------------------------------------

[window]
dimensions = { columns = 130, lines = 40 }
padding = { x= 5, y = 5 }
dynamic_padding = true
decorations = "Buttonless"
dynamic_title = true
opacity = 0.80
blur = true
startup_mode = "Windowed"
class = { general = "Alacritty", instance = "Alacritty" }
option_as_alt = "OnlyLeft"

# -- scrolling -------------------------------------------------------------------

[scrolling]
history = 10000
multiplier = 3

# -- font -------------------------------------------------------------------

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 14

# -- selection -------------------------------------------------------------------

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

# -- cursor -------------------------------------------------------------------

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
blink_timeout = 30

# -- terminal -------------------------------------------------------------------
[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", 'tmux new-session -A -s main'] }

# -- mouse -------------------------------------------------------------------

[mouse]
hide_when_typing = true
