[general]
import = [
    "~/.config/alacritty/themes/rose-pine/rose-pine.toml",
    "~/.config/alacritty/keybindings.toml"
]
live_config_reload = true

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 14

[font.bold]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux a -t main || tmux new -t main"]

[window]
blur = true
decorations = "Buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.90
option_as_alt = "OnlyLeft"
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 130
lines = 40

[window.padding]
x = 5
y = 5
